In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
data_path = Path('../Data/RAW/square_item_sales_detail_24mo.csv')
df = pd.read_csv(data_path)

In [3]:
# Fixing the column names for consistency.
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [4]:
df.head()

,date,time,time_zone,category,item,qty,price_point_name,sku,unit_price,gross_sales,...,tax,total_collected,transaction_id,payment_method,device_name,location,customer_id,event_type,unit_cost,gross_profit
0,2024-01-01,14:41,CST,Home Goods,Ceramic Coffee Mug,1,Regular,SQ-1058,16.0,16.0,...,1.32,17.32,TXN1000001,Card,Register 2,Store 01 - Austin,NaN,Payment,4.48,11.52
1,2024-01-01,15:50,CST,Apparel,Classic Denim Jacket,1,S,SQ-1001,79.0,79.0,...,6.52,85.52,TXN1000002,Card,Register 2,Store 01 - Austin,CUST16654,Payment,35.55,43.45
2,2024-01-01,13:11,CST,Electronics,Wireless Earbuds,1,Black,SQ-1048,79.0,79.0,...,6.52,85.52,TXN1000003,Card,Register 1,Store 01 - Austin,CUST02796,Payment,43.45,35.55
3,2024-01-01,15:33,CST,Apparel,Hooded Sweatshirt,2,M,SQ-1013,45.0,90.0,...,6.31,82.81,TXN1000004,Card,Register 2,Store 01 - Austin,CUST06950,Payment,18.00,40.50
4,2024-01-01,15:33,CST,Footwear,Canvas Sneakers,1,10,SQ-1027,59.0,59.0,...,3.89,51.09,TXN1000004,Card,Register 2,Store 01 - Austin,CUST06950,Payment,28.32,18.88

In [5]:
df.shape

(970838, 22)

In [7]:
df['transaction_id'].nunique()

585691

In [10]:
df.dtypes

date                 object
time                 object
time_zone            object
category             object
item                 object
qty                   int64
price_point_name     object
sku                  object
unit_price          float64
gross_sales         float64
discounts           float64
net_sales           float64
tax                 float64
total_collected     float64
transaction_id       object
payment_method       object
device_name          object
location             object
customer_id          object
event_type           object
unit_cost           float64
gross_profit        float64
dtype: object

In [8]:
# Convert the date column to datetime, format ISO08601.
df['date'] = pd.to_datetime(df['date'], format='ISO8601')

In [9]:
# Convert the time column (Formats like "14:30" or "02:15")
df['time'] = pd.to_datetime(df['time'], format='%H:%M').dt.time

In [10]:
df.dtypes

date                datetime64[ns]
time                        object
time_zone                   object
category                    object
item                        object
qty                          int64
price_point_name            object
sku                         object
unit_price                 float64
gross_sales                float64
discounts                  float64
net_sales                  float64
tax                        float64
total_collected            float64
transaction_id              object
payment_method              object
device_name                 object
location                    object
customer_id                 object
event_type                  object
unit_cost                  float64
gross_profit               float64
dtype: object

In [11]:
df.isnull().sum()*100/len(df)

date                 0.000000
time                 0.000000
time_zone            0.000000
category             0.000000
item                 0.000000
qty                  0.000000
price_point_name     0.000000
sku                  0.000000
unit_price           0.000000
gross_sales          0.000000
discounts            0.000000
net_sales            0.000000
tax                  0.000000
total_collected      0.000000
transaction_id       0.000000
payment_method       0.000000
device_name          0.000000
location             0.000000
customer_id         65.344888
event_type           0.000000
unit_cost            0.000000
gross_profit         0.000000
dtype: float64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970838 entries, 0 to 970837
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   date              970838 non-null  datetime64[ns]
 1   time              970838 non-null  object
 2   time_zone         970838 non-null  object
 3   category          970838 non-null  object
 4   item              970838 non-null  object
 5   qty               970838 non-null  int64
 6   price_point_name  970838 non-null  object
 7   sku               970838 non-null  object
 8   unit_price        970838 non-null  float64
 9   gross_sales       970838 non-null  float64
 10  discounts         970838 non-null  float64
 11  net_sales         970838 non-null  float64
 12  tax               970838 non-null  float64
 13  total_collected   970838 non-null  float64
 14  transaction_id    970838 non-null  object
 15  payment_method    970838 non-null  object
 16  device_name       970838 non-null  object
 17  location          970838 non-null  object
 18  customer_id       336445 non-null  object
 19  event_type        970838 non-null  object
 20  unit_cost         970838 non-null  float64
 21  gross_profit      970838 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(12)
memory usage: 163.0+ MB

In [13]:
df.describe()

,date,qty,unit_price,gross_sales,discounts,net_sales,tax,total_collected,unit_cost,gross_profit
count,970838,970838.000000,970838.000000,970838.000000,970838.000000,970838.000000,970838.000000,970838.000000,970838.000000,970838.000000
mean,2025-01-15 20:30:42.231968512,1.208354,41.999111,50.749456,-2.754659,47.994798,3.959895,51.954693,17.738910,26.558557
min,2024-01-01 00:00:00,-1.000000,9.500000,-129.000000,-154.800000,-129.000000,-10.640000,-139.640000,2.660000,-61.920000
25%,2024-07-16 00:00:00,1.000000,21.000000,22.000000,-3.500000,21.000000,1.730000,22.730000,7.040000,13.650000
50%,2025-01-15 00:00:00,1.000000,35.000000,40.000000,0.000000,39.000000,3.220000,42.220000,12.600000,22.400000
75%,2025-07-15 00:00:00,1.000000,59.000000,68.000000,0.000000,60.000000,4.950000,64.950000,28.320000,31.600000
max,2025-12-31 00:00:00,3.000000,129.000000,387.000000,0.000000,387.000000,31.930000,418.930000,67.080000,185.760000
std,NaN,0.532151,26.421474,41.410184,5.959887,39.640906,3.270411,42.911315,14.470461,19.466697

In [14]:
df[df['qty'] <0]

,date,time,time_zone,category,item,qty,price_point_name,sku,unit_price,gross_sales,...,tax,total_collected,transaction_id,payment_method,device_name,location,customer_id,event_type,unit_cost,gross_profit
519,2024-01-02,14:26:00,CST,Electronics,Wireless Earbuds,-1,Black,SQ-1048,79.0,-79.0,...,-6.52,-85.52,TXN1000314,Cash,Register 2,Store 09 - Chicago,NaN,Refund,43.45,-35.55
591,2024-01-02,15:52:00,CST,Footwear,Slide Sandals,-1,8,SQ-1037,24.0,-24.0,...,-1.98,-25.98,TXN1000361,Card,Register 1,Store 11 - Columbus,NaN,Refund,7.92,-16.08
643,2024-01-02,16:11:00,CST,Footwear,Leather Boots,-1,8,SQ-1029,129.0,-129.0,...,-10.64,-139.64,TXN1000393,Card,Register 1,Store 13 - Miami,NaN,Refund,67.08,-61.92
719,2024-01-02,11:19:00,CST,Accessories,Leather Belt,-1,32,SQ-1045,35.0,-35.0,...,-2.89,-37.89,TXN1000443,Card,iPad POS,Store 17 - Nashville,NaN,Refund,12.60,-22.40
729,2024-01-02,13:25:00,CST,Accessories,Baseball Cap,-1,Regular,SQ-1042,22.0,-22.0,...,-1.82,-23.82,TXN1000450,Cash,iPad POS,Store 17 - Nashville,NaN,Refund,7.04,-14.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970701,2025-12-31,16:34:00,CST,Footwear,Canvas Sneakers,-1,10,SQ-1027,59.0,-59.0,...,-4.87,-63.87,TXN1585608,Card,Register 1,Store 29 - Minneapolis,NaN,Refund,28.32,-30.68
970713,2025-12-31,09:42:00,CST,Accessories,Baseball Cap,-1,Regular,SQ-1042,22.0,-22.0,...,-1.82,-23.82,TXN1585615,Card,iPad POS,Store 29 - Minneapolis,NaN,Refund,7.04,-14.96
970718,2025-12-31,18:51:00,CST,Home Goods,Stainless Water Bottle,-1,20oz,SQ-1061,28.0,-28.0,...,-2.31,-30.31,TXN1585618,Card,Register 1,Store 29 - Minneapolis,NaN,Refund,9.80,-18.20
970761,2025-12-31,17:09:00,CST,Apparel,Hooded Sweatshirt,-1,L,SQ-1014,45.0,-45.0,...,-3.71,-48.71,TXN1585641,Card,Register 2,Store 29 - Minneapolis,NaN,Refund,18.00,-27.00
970796,2025-12-31,17:07:00,CST,Beauty,Facial Moisturizer,-1,Regular,SQ-1064,32.0,-32.0,...,-2.64,-34.64,TXN1585663,Cash,Register 1,Store 30 - Kansas City,NaN,Refund,10.24,-21.76

In [15]:
df.head()

,date,time,time_zone,category,item,qty,price_point_name,sku,unit_price,gross_sales,...,tax,total_collected,transaction_id,payment_method,device_name,location,customer_id,event_type,unit_cost,gross_profit
0,2024-01-01,14:41:00,CST,Home Goods,Ceramic Coffee Mug,1,Regular,SQ-1058,16.0,16.0,...,1.32,17.32,TXN1000001,Card,Register 2,Store 01 - Austin,NaN,Payment,4.48,11.52
1,2024-01-01,15:50:00,CST,Apparel,Classic Denim Jacket,1,S,SQ-1001,79.0,79.0,...,6.52,85.52,TXN1000002,Card,Register 2,Store 01 - Austin,CUST16654,Payment,35.55,43.45
2,2024-01-01,13:11:00,CST,Electronics,Wireless Earbuds,1,Black,SQ-1048,79.0,79.0,...,6.52,85.52,TXN1000003,Card,Register 1,Store 01 - Austin,CUST02796,Payment,43.45,35.55
3,2024-01-01,15:33:00,CST,Apparel,Hooded Sweatshirt,2,M,SQ-1013,45.0,90.0,...,6.31,82.81,TXN1000004,Card,Register 2,Store 01 - Austin,CUST06950,Payment,18.00,40.50
4,2024-01-01,15:33:00,CST,Footwear,Canvas Sneakers,1,10,SQ-1027,59.0,59.0,...,3.89,51.09,TXN1000004,Card,Register 2,Store 01 - Austin,CUST06950,Payment,28.32,18.88

In [16]:
df.groupby('transaction_id').count()

,date,time,time_zone,category,item,qty,price_point_name,sku,unit_price,gross_sales,...,net_sales,tax,total_collected,payment_method,device_name,location,customer_id,event_type,unit_cost,gross_profit
transaction_id,,,,,,,,,,,,,,,,,,,,,
TXN1000001,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
TXN1000002,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
TXN1000003,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
TXN1000004,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
TXN1000005,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,0,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TXN1585687,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
TXN1585688,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,0,4,4,4
TXN1585689,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
TXN1585690,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
TXN1585691,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,0,2,2,2

In [17]:
df_test = df['transaction_id'].value_counts().reset_index()

In [18]:
df_test['count'].value_counts()

count
1    327448
2    160319
3     68944
4     28980
Name: count, dtype: int64

In [19]:
df_test['count'].mean()

np.float64(1.657594192159347)

In [20]:
df[df['transaction_id'] == 'TXN1585688']

,date,time,time_zone,category,item,qty,price_point_name,sku,unit_price,gross_sales,...,tax,total_collected,transaction_id,payment_method,device_name,location,customer_id,event_type,unit_cost,gross_profit
970830,2025-12-31,15:58:00,CST,Beauty,Bath Bomb Trio,1,Regular,SQ-1067,15.0,15.0,...,0.99,12.99,TXN1585688,Cash,Register 1,Store 30 - Kansas City,NaN,Payment,4.35,7.65
970831,2025-12-31,15:58:00,CST,Apparel,Hooded Sweatshirt,1,M,SQ-1013,45.0,45.0,...,2.23,29.23,TXN1585688,Cash,Register 1,Store 30 - Kansas City,NaN,Payment,18.00,9.00
970832,2025-12-31,15:58:00,CST,Footwear,Running Shoes,1,9,SQ-1034,89.0,89.0,...,5.87,77.07,TXN1585688,Cash,Register 1,Store 30 - Kansas City,NaN,Payment,44.50,26.70
970833,2025-12-31,15:58:00,CST,Apparel,Cotton Crew T-Shirt,1,XL,SQ-1008,21.0,21.0,...,1.73,22.73,TXN1585688,Cash,Register 1,Store 30 - Kansas City,NaN,Payment,7.35,13.65

In [21]:
df[df['discounts'] >= df['gross_sales']]

,date,time,time_zone,category,item,qty,price_point_name,sku,unit_price,gross_sales,...,tax,total_collected,transaction_id,payment_method,device_name,location,customer_id,event_type,unit_cost,gross_profit
519,2024-01-02,14:26:00,CST,Electronics,Wireless Earbuds,-1,Black,SQ-1048,79.0,-79.0,...,-6.52,-85.52,TXN1000314,Cash,Register 2,Store 09 - Chicago,NaN,Refund,43.45,-35.55
591,2024-01-02,15:52:00,CST,Footwear,Slide Sandals,-1,8,SQ-1037,24.0,-24.0,...,-1.98,-25.98,TXN1000361,Card,Register 1,Store 11 - Columbus,NaN,Refund,7.92,-16.08
643,2024-01-02,16:11:00,CST,Footwear,Leather Boots,-1,8,SQ-1029,129.0,-129.0,...,-10.64,-139.64,TXN1000393,Card,Register 1,Store 13 - Miami,NaN,Refund,67.08,-61.92
719,2024-01-02,11:19:00,CST,Accessories,Leather Belt,-1,32,SQ-1045,35.0,-35.0,...,-2.89,-37.89,TXN1000443,Card,iPad POS,Store 17 - Nashville,NaN,Refund,12.60,-22.40
729,2024-01-02,13:25:00,CST,Accessories,Baseball Cap,-1,Regular,SQ-1042,22.0,-22.0,...,-1.82,-23.82,TXN1000450,Cash,iPad POS,Store 17 - Nashville,NaN,Refund,7.04,-14.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970701,2025-12-31,16:34:00,CST,Footwear,Canvas Sneakers,-1,10,SQ-1027,59.0,-59.0,...,-4.87,-63.87,TXN1585608,Card,Register 1,Store 29 - Minneapolis,NaN,Refund,28.32,-30.68
970713,2025-12-31,09:42:00,CST,Accessories,Baseball Cap,-1,Regular,SQ-1042,22.0,-22.0,...,-1.82,-23.82,TXN1585615,Card,iPad POS,Store 29 - Minneapolis,NaN,Refund,7.04,-14.96
970718,2025-12-31,18:51:00,CST,Home Goods,Stainless Water Bottle,-1,20oz,SQ-1061,28.0,-28.0,...,-2.31,-30.31,TXN1585618,Card,Register 1,Store 29 - Minneapolis,NaN,Refund,9.80,-18.20
970761,2025-12-31,17:09:00,CST,Apparel,Hooded Sweatshirt,-1,L,SQ-1014,45.0,-45.0,...,-3.71,-48.71,TXN1585641,Card,Register 2,Store 29 - Minneapolis,NaN,Refund,18.00,-27.00
970796,2025-12-31,17:07:00,CST,Beauty,Facial Moisturizer,-1,Regular,SQ-1064,32.0,-32.0,...,-2.64,-34.64,TXN1585663,Cash,Register 1,Store 30 - Kansas City,NaN,Refund,10.24,-21.76

In [22]:
df[['discounts', 'gross_sales']]

        discounts  gross_sales
0             0.0         16.0
1             0.0         79.0
2             0.0         79.0
3           -13.5         90.0
4           -11.8         59.0
...           ...          ...
970833        0.0         21.0
970834        0.0        158.0
970835       -6.8         34.0
970836        0.0        118.5
970837       -9.8         49.0

[970838 rows x 2 columns]

In [23]:
df[df.duplicated()]

Empty DataFrame
Columns: [date, time, time_zone, category, item, qty, price_point_name, sku, unit_price, gross_sales, discounts, net_sales, tax, total_collected, transaction_id, payment_method, device_name, location, customer_id, event_type, unit_cost, gross_profit]
Index: []

[0 rows x 22 columns]

In [24]:
(df['qty']*df['unit_price']- df['gross_sales']).value_counts()

0.0    970838
Name: count, dtype: int64

In [25]:
(df['gross_sales'] + df['discounts'] - df['net_sales']).value_counts()

 0.000000e+00    969305
 1.776357e-15      1076
-3.552714e-15       457
Name: count, dtype: int64

In [26]:
df['net_sales'] - df['unit_cost'] * df['qty'] - df['gross_profit']

0         0.000000e+00
1         0.000000e+00
2         0.000000e+00
3         0.000000e+00
4         3.552714e-15
              ...
970833    0.000000e+00
970834    0.000000e+00
970835    0.000000e+00
970836    0.000000e+00
970837    3.552714e-15
Length: 970838, dtype: float64

In [27]:
df.columns

Index(['date', 'time', 'time_zone', 'category', 'item', 'qty',
       'price_point_name', 'sku', 'unit_price', 'gross_sales', 'discounts',
       'net_sales', 'tax', 'total_collected', 'transaction_id',
       'payment_method', 'device_name', 'location', 'customer_id',
       'event_type', 'unit_cost', 'gross_profit'],
      dtype='object')

In [28]:
df['event_type'].unique()

array(['Payment', 'Refund'], dtype=object)

In [29]:
df_test = df[df['event_type'] =='Payment']

In [30]:
df_test['qty'].min()

1

In [31]:
df_test = df[df['event_type'] =='Refund']

In [32]:
df_test['qty'].max()

-1

In [34]:
df.to_csv('Retail POS Data Cleaned.csv', index=False)

In [35]:
cols = ['time_zone',
'category',
'item',
'price_point_name',
'sku',
'payment_method',
'device_name',
'location',
'customer_id',
'event_type',
'transaction_id']

In [38]:
df[cols].apply(lambda x: x.str.len().max())

time_zone            3.0
category            11.0
item                22.0
price_point_name     7.0
sku                  7.0
payment_method       5.0
device_name         10.0
location            23.0
customer_id          9.0
event_type           7.0
transaction_id      10.0
dtype: float64

In [39]:
df['transaction_id']

0         TXN1000001
1         TXN1000002
2         TXN1000003
3         TXN1000004
4         TXN1000004
             ...
970833    TXN1585688
970834    TXN1585689
970835    TXN1585690
970836    TXN1585691
970837    TXN1585691
Name: transaction_id, Length: 970838, dtype: object